### ISSUE TITLE
Stopped working today in Turkey

### ISSUE THREAD

**Issue by Bloomfear** [cheytacllc/GUI-for-GoodbyeDPI#1]
Is there anything i can do to make it work again? Neither wikipedia nor imgur can be reached.

Neden durdu bunun çalışması bugün?

**Comment by mguludag** [comment]
Hello, 
What is your ISP?

**Comment by Bloomfear** [comment]
Kablonet

It was working before. It just stopped today.

**Comment by mguludag** [comment]
Is your dnscrypt-proxy starts running during you clicked start button in program? And show the dnscrypt-proxy log screen and system dns settings page then i investigate this problem.

**Comment by Bloomfear** [comment]
Here are the both screens;

![dnscrypt-proxy log](https://user-images.githubusercontent.com/24738981/54848393-38c8ef80-4cf2-11e9-8daa-295b7544301c.JPG)
![system dns settings](https://user-images.githubusercontent.com/24738981/54848398-3c5c7680-4cf2-11e9-87a9-e4160d8b8000.JPG)

And yes dnscrypt-proxy is working;

![dnscrypt-proxy](https://user-images.githubusercontent.com/24738981/54848522-880f2000-4cf2-11e9-9f7e-0098e0ef5b07.JPG)
![goodbydpi](https://user-images.githubusercontent.com/24738981/54848565-aaa13900-4cf2-11e9-8f02-429f959ed328.JPG)

**Comment by mguludag** [comment]
Have you ever tried the change settings to "Ayarlar > Özel Parametre Kullan > Hızlı Ayarlar > [-3] or [-2] or [-1] " ?

**Comment by Bloomfear** [comment]
I just tried all 4 of them, none worked.

**Comment by mguludag** [comment]
Ok. After this results I think goodbyedpi cant pass the blocks on some ISPs. Maybe goodbyedpi developer ValdikSS will fix this issue making new update.

**Comment by tosunkaya** [comment]
> Is there anything i can do to make it work again? Neither wikipedia nor imgur can be reached.
> 
> Neden durdu bunun çalışması bugün?

it's not working ANYMORE on Turk Telekom too. It was working on Turkcell Superonline, Turk Telekom, Vodafone in Turkey. Also mobile apps that can bypass dpi aren't working. This is too bad. @cheytacllc please help us. ❤Imgur, Wiki

Edit: Still works for SO.

**Comment by mguludag** [comment]
Today I tried and its working, btw I'm using vodafone.

**Comment by tosunkaya** [comment]
> Today I tried and its working, btw I'm using vodafone.

still works for superonline and vodafone (mobile). but blocked on turk telekom. whatever wisdom popular paid vpns (nord, express etc) are blocked on superonline and accesable on turk telekom 😂🤣 You are the man.

**Comment by quyirah** [comment]
Is it working on Kablonet?
